name: OnPush

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          dockerfile: C:\Users\timot\OneDrive\Documents\M1\DevOps\20200332\DockerFile
          push: true
          tags: erebexii/devops_weather:latest
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

