name: OnPush

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use API token
        env:
          API_TOKEN: ${{ secrets.API_WEATHER_TOKEN }}
        run: |
          echo "API token: $API_TOKEN"
