name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t erebexii/devops_weather:latest .

      - name: Push Docker image to Docker Hub
        run: docker push erebexii/devops_weather:latest

      - name: Login to Azure container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push docker image to Azure container registry
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.REGISTRY_LOGIN_SERVER }}/{{secrets.EFREI_IDENTIFIER}}:v1

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure container instance
        uses: azure/aci-deploy@v1
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          dns-name-label: devops-{{secrets.EFREI_IDENTIFIER}}
          image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/{{secrets.EFREI_IDENTIFIER}}:v1
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          name: {{secrets.EFREI_IDENTIFIER}}
          location: 'france central'
          secure-environment-variables: API_WEATHER_TOKEN=${{ secrets.API_WEATHER_TOKEN }}
          ports: 8080